name: tests

on:
  pull_request: {}
  workflow_call:

permissions:
  contents: write
  actions: write
  checks: write
  issues: write

jobs:
  test:
    name: Package tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: move project to temporal folder
        run: mkdir temporal_repo_folder && ls && find * -maxdepth 0 -not -name temporal_repo_folder -exec mv {} temporal_repo_folder/ \;
      - name: Check GITHUB_TOKEN
        run: |
          if [ -z "${{ secrets.GITHUB_TOKEN }}" ]; then
            echo "GITHUB_TOKEN is not set."
            exit 1
          else
            echo "GITHUB_TOKEN is set."
          fi
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        id: test-step
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          packageMode: true
          unityVersion: '2021.3.24f1'
          projectPath: temporal_repo_folder
          artifactsPath: 'artifacts'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results
          path: ${{ steps.test-step.outputs.artifactsPath }}
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            ./${{ steps.test-step.outputs.artifactsPath }}/*.xml
