name: tests

on:
  pull_request: {}
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # with:
        #   sparse-checkout: .
      # - uses: actions/cache@v4
      #   with:
      #     path: Library
      #     key: Library-${{ hashFiles('Assets/**', 'Editor/**', 'Runtime/**', 'Tests/**') }}
      #     restore-keys: |
      #       Library-
      - name: a list
        run: ls
      - name: move project to temporal folder
        run: mkdir temporal_repo_folder && ls && find * -maxdepth 0 -not -name temporal_repo_folder -exec mv {} temporal_repo_folder/ \;
      - name: another list
        run: ls
      - name: a list of temporal
        run: ls temporal_repo_folder
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          packageMode: true
          unityVersion: 2021.3.24f1
          projectPath: temporal_repo_folder
      



